// import 'package:flutter/foundation.dart';
// import 'package:flutter/material.dart';


class AppLocalizations {
  // ignore: unused_field
  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'add_a_group_name': 'Add a group name',
      'add_group_members': 'Add Group Members',
      'advanced_options': 'Advanced Options',
      'api_key_error': 'Please enter the Chat API Key',
      'attachment': 'attachment',
      'attachments': 'attachments',
      'cancel': 'Cancel',
      'chat_api_key': 'Chat API Key',
      'chats': 'Chats',
      'choose_a_group_chat_name': 'Choose a group chat name',
      'connected': 'Connected',
      'create_a_group': 'Create a Group',
      'custom_settings': 'Custom settings',
      'delete': 'Delete',
      'delete_conversation_are_you_sure':
          'Are you sure you want to delete this conversation?',
      'delete_conversation_title': 'Delete Conversation',
      'disconnected': 'Disconnected',
      'error_connecting': 'Error connecting, retry',
      'files': 'Files',
      'files_appear_here': 'Files sent in this chat will appear here',
      'group_shared_with_user_appear_here':
          'Group shared with User will appear here.',
      'last_seen': 'Last seen',
      'leave': 'Leave',
      'leave_conversation': 'Leave conversation',
      'leave_conversation_are_you_sure':
          'Are you sure you want to leave this conversation?',
      'leave_group': 'Leave Group',
      'loading': 'Loading...',
      'login': 'Login',
      'long_press_message': 'Long-press an important message and\nchoose',
      'matches_for': 'Matches for',
      'member': 'Member',
      'members': 'Members',
      'mentions': 'Mentions',
      'message': 'Message',
      'message_channel_description': 'Channel used for showing messages',
      'message_channel_name': 'Message channel',
      'more': 'more',
      'mute_group': 'Mute group',
      'mute_user': 'Mute user',
      'name': 'Name',
      'name_of_group_chat': 'Name of Group Chat',
      'new_chat': 'New Chat',
      'new_direct_message': 'New direct message',
      'new_group': 'New group',
      'no_chats_here_yet': 'No chats here yet...',
      'no_files': 'No Files',
      'no_media': 'No Media',
      'no_mentions_exist_yet': 'No mentions exist yet...',
      'no_pinned_items': 'No pinned items',
      'no_results': 'No results...',
      'no_shared_groups': 'No Shared Groups',
      'no_title': 'No title',
      'no_user_matches_these_keywords': 'No user matches these keywords...',
      'ok': 'OK',
      'online': 'Online',
      'on_the_platform': 'On the platform',
      'operation_could_not_be_completed':
          'The operation couldn\'t be completed.',
      'owner': 'Owner',
      'photos_and_videos': 'Photos & Videos',
      'photos_or_videos_will_appear_here':
          'Photos or videos sent in this chat will \nappear here',
      'pinned_messages': 'Pinned Messages',
      'pin_to_conversation': 'Pin to conversation',
      'reconnecting': 'Reconnecting...',
      'remove': 'Remove',
      'remove_from_group': 'Remove From Group',
      'remove_member': 'Remove member',
      'remove_member_are_you_sure':
          'Are you sure you want to remove this member?',
      'search': 'Search',
      'select_user_to_try_flutter_sdk': 'Select a user to try the Flutter SDK',
      'shared_groups': 'Shared Groups',
      'sign_out': 'Sign out',
      'something_went_wrong_error_message': 'Something went wrong',
      'stream_sdk': 'Stream SDK',
      'stream_test_account': 'Stream test account',
      'to': 'To',
      'type_a_name_hint': 'Type a name',
      'user_id': 'User ID',
      'user_id_error': 'Please enter the User ID',
      'username_optional': 'Username (optional)',
      'user_token': 'User Token',
      'user_token_error': 'Please enter the user token',
      'view_info': 'View info',
      'welcome_to_stream_chat': 'Welcome to Stream Chat',
    },
    'it': {
      'add_a_group_name': 'Aggiungi un nome al gruppo',
      'add_group_members': 'Aggiungi un membro',
      'advanced_options': 'Opzioni Avanzate',
      'api_key_error': 'Per favore inserisci l\'API Key',
      'attachment': 'allegato',
      'attachments': 'allegati',
      'cancel': 'Annulla',
      'chat_api_key': 'Chat API Key',
      'chats': 'Conversazioni',
      'choose_a_group_chat_name': 'Scegli un nome per il gruppo',
      'connected': 'Connesso',
      'create_a_group': 'Crea un Gruppo',
      'custom_settings': 'Opzioni Personalizzate',
      'delete': 'Cancella',
      'delete_conversation_are_you_sure':
          'Sei sicuro di voler eliminare la conversazione?',
      'delete_conversation_title': 'Elimina Conversazione',
      'disconnected': 'Disconnesso',
      'error_connecting': 'Errore durante la connessione, riprova',
      'files': 'File',
      'files_appear_here': 'I file inviati in questa chat compariranno qui',
      'group_shared_with_user_appear_here':
          'I gruppi in comune con quest\'utente compariranno qui',
      'last_seen': 'Ultimo accesso',
      'leave': 'Lascia',
      'leave_conversation': 'Lascia conversazione',
      'leave_conversation_are_you_sure':
          'Sei sicuro di voler lasciare questa conversazione?',
      'leave_group': 'Lascia Gruppo',
      'loading': 'Caricamento...',
      'login': 'Login',
      'long_press_message': 'Premi a lungo su un messaggio importante e scegli',
      'matches_for': 'Risultati per',
      'member': 'Membro',
      'members': 'Membri',
      'mentions': 'Menzioni',
      'message': 'Messaggi',
      'message_channel_description': 'Canale usato per mostrare i messaggi',
      'message_channel_name': 'Invia un messaggio al canale',
      'more': 'altro',
      'mute_group': 'Silenzia gruppo',
      'mute_user': 'Silenzia utente',
      'name': 'Nome',
      'name_of_group_chat': 'Nome del gruppo',
      'new_chat': 'Nuova conversazione',
      'new_direct_message': 'Nuovo messaggio diretto',
      'new_group': 'Nuovo gruppo',
      'no_chats_here_yet': 'Ancora nessun messaggio...',
      'no_files': 'Nessun File',
      'no_media': 'Nessun Media',
      'no_mentions_exist_yet': 'Ancora nessuna menzione...',
      'no_pinned_items': 'Nessun messaggio in evidenza',
      'no_results': 'Nessun risultato...',
      'no_shared_groups': 'Nessun gruppo in comune',
      'no_title': 'Nessun titolo',
      'no_user_matches_these_keywords': 'Nessun utente per questa ricerca...',
      'ok': 'OK',
      'online': 'Online',
      'on_the_platform': 'Sulla piattaforma',
      'operation_could_not_be_completed':
          'Non é stato possibile completare l\'operazione.',
      'owner': 'Proprietario',
      'photos_and_videos': 'Foto & Video',
      'photos_or_videos_will_appear_here':
          'Foto or video inviati in questa chat \ncompariranno qui',
      'pinned_messages': 'Messaggi in evidenza',
      'pin_to_conversation': 'Metti in evidenza',
      'reconnecting': 'Riconnessione...',
      'remove': 'Rimuovi',
      'remove_from_group': 'Rimuovi Dal Gruppo',
      'remove_member': 'Rimuovi membro',
      'remove_member_are_you_sure':
          'Sei sicuro di voler rimuovere questo membro?',
      'search': 'Cerca',
      'select_user_to_try_flutter_sdk':
          'Seleziona un utente per provare l\'SDK Flutter',
      'shared_groups': 'Gruppi in comune',
      'sign_out': 'Sign out',
      'something_went_wrong_error_message': 'Qualcosa é andato storto',
      'stream_sdk': 'Stream SDK',
      'stream_test_account': 'Account di test',
      'to': 'A',
      'type_a_name_hint': 'Scrivi un nome',
      'user_id': 'User ID',
      'user_id_error': 'Per favore inserisci l\'ID dell\'utente',
      'username_optional': 'Username (opzionale)',
      'user_token': 'Token Utente',
      'user_token_error': 'Per favore inserisci il token',
      'view_info': 'Vedi info',
      'welcome_to_stream_chat': 'Benvenuto in Stream Chat',
    },
    'zh-hans':{
      'add_a_group_name': '添加组名称',
      'add_group_members': '添加组成员',
      'advanced_options': '高级选项',
      'api_key_error': 'Please enter the Chat API Key',
      'attachment': '附件',
      'attachments': '附件',
      'cancel': '取消',
      'chat_api_key': 'Chat API Key',
      'chats': '聊天',
      'choose_a_group_chat_name': '选择群聊名称',
      'connected': 'Connected',
      'create_a_group': '创建群',
      'custom_settings': '通用设置',
      'delete': '删除',
      'delete_conversation_are_you_sure':
          '您确定要删除此对话吗？',
      'delete_conversation_title': '删除会话',
      'disconnected': '断开连接',
      'error_connecting': '连接错误 重试',
      'files': '文件',
      'files_appear_here': '在此聊天中发送的文件将显示在此处',
      'group_shared_with_user_appear_here':
          '与用户共享的组将显示在此处。',
      'last_seen': 'Last seen',
      'leave': 'Leave',
      'leave_conversation': 'Leave conversation',
      'leave_conversation_are_you_sure':
          'Are you sure you want to leave this conversation?',
      'leave_group': '最后一次看到',
      'loading': 'Loading...',
      'login': '登录',
      'long_press_message': '长按重要信息并选择',
      'matches_for': 'Matches for',
      'member': 'Member',
      'members': 'Members',
      'mentions': 'Mentions',
      'message': 'Message',
      'message_channel_description': 'Channel used for showing messages',
      'message_channel_name': 'Message channel',
      'more': 'more',
      'mute_group': 'Mute group',
      'mute_user': 'Mute user',
      'name': 'Name',
      'name_of_group_chat': 'Name of Group Chat',
      'new_chat': 'New Chat',
      'new_direct_message': 'New direct message',
      'new_group': 'New group',
      'no_chats_here_yet': 'No chats here yet...',
      'no_files': 'No Files',
      'no_media': 'No Media',
      'no_mentions_exist_yet': 'No mentions exist yet...',
      'no_pinned_items': 'No pinned items',
      'no_results': 'No results...',
      'no_shared_groups': 'No Shared Groups',
      'no_title': 'No title',
      'no_user_matches_these_keywords': 'No user matches these keywords...',
      'ok': 'OK',
      'online': 'Online',
      'on_the_platform': 'On the platform',
      'operation_could_not_be_completed':
          'The operation couldn\'t be completed.',
      'owner': 'Owner',
      'photos_and_videos': 'Photos & Videos',
      'photos_or_videos_will_appear_here':
          'Photos or videos sent in this chat will \nappear here',
      'pinned_messages': 'Pinned Messages',
      'pin_to_conversation': 'Pin to conversation',
      'reconnecting': 'Reconnecting...',
      'remove': 'Remove',
      'remove_from_group': 'Remove From Group',
      'remove_member': 'Remove member',
      'remove_member_are_you_sure':
          'Are you sure you want to remove this member?',
      'search': 'Search',
      'select_user_to_try_flutter_sdk': 'Select a user to try the Flutter SDK',
      'shared_groups': 'Shared Groups',
      'sign_out': 'Sign out',
      'something_went_wrong_error_message': 'Something went wrong',
      'stream_sdk': 'Stream SDK',
      'stream_test_account': 'Stream test account',
      'to': 'To',
      'type_a_name_hint': 'Type a name',
      'user_id': 'User ID',
      'user_id_error': 'Please enter the User ID',
      'username_optional': 'Username (optional)',
      'user_token': 'User Token',
      'user_token_error': 'Please enter the user token',
      'view_info': 'View info',
      'welcome_to_stream_chat': 'Welcome to Stream Chat',
    }
  };
}